print ("Alexander")
print ("November 27th 2022")
print ("I am signing up for Replit's 100 days of Python challenge!")
print ("I will make sure to spend time every day coding along, for the minimum of 10 minutes a day.")
print ("I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happen to be. No excuses for not coding from the middle of a field!")
print ("I am feeling 🤩")
print ("You can follow my progress at replit.com/@amarquina80")