print("=== Your Adventure Simulator ===")
print(""" You'll be asked a bunch of questions then we'll make you up an amazing story with YOU as the star! 😎""")
print()
name = input("Your name: ")
enemy = input ("Your worst enemy's name: ")
superPower = input ("Your super power: ")
print()
print("Our story begins as our hero name approaches a foreboding castle...")
print("Suddenly a bolt of lightning striked the ground at the feet of", name)
print("'Our final battle begins!' shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superPower, "which means they'll win quite easily")

# 
print("=== Your Adventure Simulator ===")
print(""" You'll be asked a bunch of questions then we'll make you up an amazing story with YOU as the star! 😎""")
print()
name = input("Your name: ")
enemy = input ("Your worst enemy's name: ")
superPower = input ("Your super power: ")
print()
print("Our story begins as our hero,", "\033[33m",name ,"\033[0m"",approaches a foreboding castle...")
print("Suddenly a bolt of lightning striked the ground at the feet of", name)
print("\033[31m","'Our final battle begins!'","\033[0m" ,"shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superPower, "which means they'll win quite easily")

print("Uh, oh, you've been given a","\033[36m", "warning", "\033[0m","for being a bad, bad person.")